CREATE TABLE USUARIO (
	USR_COD INT NOT NULL AUTO_INCREMENT,
    USR_SENHA VARCHAR(20) NOT NULL,
    USR_EMAIL VARCHAR(60) NOT NULL,
    USR_FONE VARCHAR(20) NOT NULL,
    USR_NOME VARCHAR(60) NOT NULL,
    USR_CPF VARCHAR(16),
    USR_RG VARCHAR(20),
    USR_DATANASC DATE,
    USR_FONE VARCHAR(20),
    USR_CIDADE VARCHAR(40),
    USR_DATACAD DATE NOT NULL, /*Data em que o usuário foi cadastrado, guardar data atual, sem permitir alteração*/
    PRIMARY KEY(CLI_COD)
);

CREATE TABLE CONTA (
	CONTA_COD INT NOT NULL AUTO_INCREMENT,
    CONTA_USRCOD INT NOT NULL,
    CONTA_NOME VARCHAR(40) NOT NULL,
    CONTA_TIPO INT NOT NULL, /*COMBO BOX EX: 1 - Conta Corrente, 2 - Poupança, 3 - Cartão de Crédito, etc...*/
    CONTA_SALDO DECIMAL(6,2) NOT NULL,
    CONTA_DATACAD DATE NOT NULL, /*Data em que a conta foi criada, guardar data atual, sem permitir alteração*/
    PRIMARY KEY(CONTA_COD),
    FOREIGN KEY(CONTA_USRCOD) REFERENCES USUARIO(USR_COD)
);

CREATE TABLE CATEGORIA (
	CATEG_COD INT NOT NULL AUTO_INCREMENT,
    CATEG_NOME VARCHAR(40) NOT NULL,
    CATEG_TIPO INT NOT NULL, /*COMBO BOX EX: 1 - Alimentação, 2 - Transporte, 3 - Lazer, 4 - Outros, etc...*/
    PRIMARY KEY(CATEG_COD)
);

CREATE TABLE TRANSACOES (
	TRSC_COD INT NOT NULL AUTO_INCREMENT,
    TRSC_CONTACOD INT NOT NULL,
    TRSC_CATEGCOD INT NOT NULL,
    TRSC_VALOR DECIMAL(6,2) NOT NULL,
    TRSC_DESCRICAO VARCHAR(60) NOT NULL,
    TRSC_DATA DATETIME NOT NULL, /*Data e hora em que a transação foi realizada*/
    PRIMARY KEY(TRASC_COD),
    FOREIGN KEY(TRSC_CONTACOD) REFERENCES CONTA(CONTA_COD),
    FOREIGN KEY(TRSC_CATEGCOD) REFERENCES CATEGORIA(CATEG_COD)
);

CREATE TABLE METAS (
	METAS_COD INT NOT NULL AUTO_INCREMENT,
    METAS_USRCOD INT NOT NULL,
    METAS_DESCRICAO VARCHAR(40) NOT NULL,
    METAS_VALOR DECIMAL(6,2) NOT NULL,
    METAS_DATALIMITE DATE NOT NULL,
    PRIMARY KEY(METAS_COD),
    FOREIGN KEY(METAS_USRCOD) REFERENCES USUARIO(USR_COD)
);